# Description: Configuration file for test
# 
N_E: 800
N_I: 200
P_EE: 0.1
P_EI: 0.1
P_IE: 0.1
P_II: 0.2
RandomStrength : 1
factor_mn: 1 # scaling factor

taud_E: 2 #synaptic decay time(dont change!)
taud_I: 5 #synaptic decay time

num_phase: 9 # number of phases to test
trails: 1 # number of trails

eta_E: 2
eta_I: 2

delta_E: 0.04 # variance of bias input to E (lorentzian distribution)
delta_I: 0.04


mu: 0
sigma: 0.2
sigma_rand: 0.1   # 100/(N_E+N_I)


dt: 0.1 #(ms/step)
T_pre: 200 # length of time before sti (ms)
T_sti: 10 # length of time for sti (ms)

T_after: 390 # length of time after sti (ms)

InputStrength: 10 #Input Strength (maybe chage to norm in the future)
# InputStrength: 1
#10

color_Go: '#1C63A9'
color_Nogo: '#009999'