# Description: Configuration file for test
# 
N_E: 800
N_I: 200
P_EE: 0.1
P_EI: 0.1
P_IE: 0.05
P_II: 0.4
RandomStrength : 1
factor_mn: 1 # scaling factor for the mean of W_rank1
taud_E: 2
taud_I: 5
# taud_E:
#  - 2
#  - 100
# taud_I:
#  - 5
#  - 100
# ratio_fast: 0.2 # ratio of fast synapses

eta_E: 0 # average bias input to E (lorentzian distribution)
eta_I: 2
delta_E: 0 # variance of bias input to E (lorentzian distribution)
delta_I: 0.05

mu: 0
sigma: 0.1
# mu_rand: 0.1  # 1/(N_E+N_I)
sigma_rand: 0.1   # 100/(N_E+N_I)
dt: 0.1 #(ms/step)
T_pre: 100 # length of time before sti (ms)
T_sti: 10 # length of time for sti (ms)
T_after: 100 # length of time after sti (ms)
InputStrength: 10 #Input Strength (maybe chage to norm in the future)
# norm_input: 1 # Normalization of input
color_Go: '#1C63A9'
color_Nogo: '#009999'