# Description: Configuration file for Lowrank SNN with I synapses defined
# Go-Nogo task
N_E: 800
N_I: 200
P_EE: 0.1
P_EI: 0.1
P_IE: 0.1
P_II: 0.1
RandomStrength : 1
factor_mn: 1
taud_E: 2
taud_I: 5
# taud_E:
#  - 2
#  - 100
# taud_I:
#  - 5
#  - 100
# ratio_fast: 0.2 # ratio of fast synapses
mu: 0
sigma: 0.1
# mu_rand: 0.1  # 1/(N_E+N_I)
sigma_rand: 0.1   # 100/(N_E+N_I)
dt: 1 #(ms/step)
T_pre: 50 # length of time before sti (ms)
T_sti: 100 # length of time for sti (ms)
T_after: 150 # length of time after sti (ms)
InputStrength: 2 #Input Strength (maybe chage to norm in the future)
# norm_input: 1 # Normalization of input
color_Go: '#1C63A9'
color_Nogo: '#009999'