N_E: 4000
N_I: 1000
RandomStrength : 0.5
taud_E: 2
taud_I: 5
mu: 1
sigma: 10
mu_rand: 0.0002  # 1/(N_E+N_I)
sigma_rand: 0.02   # 100/(N_E+N_I)
dt: 0.01 #(ms/step)
T_pre: 5 # length of time before sti (ms)
T_sti: 10 # length of time for sti (ms)
T_after: 15 # length of time after sti (ms)
InputStrength: 3 #Input Strength (maybe chage to norm in the future)
norm_input: 0.1 # Normalization of input
color_Go: '#1C63A9'
color_Nogo: '#009999'