# Description: Configuration file for test different parameters 
# to see whether the oscilaltion happens accordign to 
# the pridiction of the theory
# 
N_E: 800
N_I: 200
# N_E: 3200
# N_I: 800
P_EE: 0.1
P_EI: 0.1
# P_EI: 0.8

# P_IE: 0.1
P_IE: 0.05
# P_IE: 0.5
# P_IE: 0.8
# P_II: 0.1
P_II: 0.4
RandomStrength : 1
factor_mn: 1 # scaling factor fßor the mean of W_rank1
taud_E: 2 #synaptic decay time(dont change!)
taud_I: 5 #synaptic decay time

num_phase: 9 # number of phases to test
trails: 1 # number of trails

# eta_E: 0.1 # average bias input to E (lorentzian distribution)
# eta_I: 0.2
# eta_E: 2     # average bias input to E (lorentzian distribution)
eta_E: 1
# eta_I: 3
# eta_I: 1
# eta_I: 2
# eta_I: 0.05
eta_I: 1

# eta_I: 0.05
# delta_E: 0.04 # variance of bias input to E (lorentzian distribution)
# delta_I: 0.04
delta_E: 0.1 # variance of bias input to E (lorentzian distribution)
delta_I: 0.1

mu: 0
sigma: 0.2
sigma_rand: 0.1   # 100/(N_E+N_I)


dt: 0.1 #(ms/step)
T_pre: 200 # length of time before sti (ms)
T_sti: 10 # length of time for sti (ms)
# T_after: 290 # length of time after sti (ms)
T_after: 790 # length of time after sti (ms)

InputStrength: 0 #Input Strength (maybe chage to norm in the future)
#5，4，3，2

# norm_input: 1 # Normalization of input
color_Go: '#1C63A9'
color_Nogo: '#009999'